### ISSUE TITLE
Add Docker Image for Android API 34

### ISSUE THREAD

**Issue by carstenhag** [faberNovel/docker-android#122]
(Including JDK17 probably?)

**Comment by ikanjioctavebio** [comment]
I would also like a docker image for android api 34

**Comment by flolom** [comment]
Hello, [version 1.8.0](https://github.com/faberNovel/docker-android/releases/tag/v1.8.0) has been released and supports API 34 and JDK 17

You can use `docker://fabernovel/android:api-34-v1.8.0` in your github action file
