### ISSUE TITLE
Publish Github Action

### ISSUE THREAD

**Issue by sjcqs** [faberNovel/docker-android#55]
The action is developped but not yet published. 

https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace

**Comment by sjcqs** [comment]
We might need to move `action.yml` in the root directory since Github is looking for this file there.

**Comment by sjcqs** [comment]
https://github.com/faberNovel/docker-android/pull/56#discussion_r424272939

**Comment by sjcqs** [comment]
Small enhancement for the documentation: 
Add `yml` to add syntax coloration

**Comment by vincentbrison** [comment]
https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace#about-publishing-actions -> We should be good by just moving `action.yml` to the root folder.
