### ISSUE TITLE
Add variants without gcloud / python

### ISSUE THREAD

**Issue by vincentbrison** [faberNovel/docker-android#68]
To support Firebase Test Lab, a lot of software is needed, with gcloud and python, increasing the base image size.
We should investigate the cost (image size mainly) to provide variants without Firebase Test Lab support.
Then we would have following variants:
- api
- api-ftl
- api-ndk
- api-ftl-ndk

Since we support last two Android API, it would make 8 variants. I guess it is not a problem?

What do you think about it @sjcqs ?

**Comment by sjcqs** [comment]
Maybe we should compare image size with/without Google cloud SDK as a starting point.

If it's a small diff it might not worth the effort

**Comment by vincentbrison** [comment]
Yes, lets gather some data and we will see. If it worth the effort, it should be easy to add an option to enable / disable FTL support in Dockerfile and scripts, and it should also be easy to update GitHub Actions as we already using matrix builds.
