### ISSUE TITLE
Move scripts back to bash and clean syntax

### ISSUE THREAD

**Issue by vincentbrison** [faberNovel/docker-android#70]
Evaluate the possibility of moving project script back to bash, and clean them using https://google.github.io/styleguide/shellguide.html.

Concerned scripts are:
- [ci_cd.sh](https://github.com/faberNovel/docker-android/blob/develop/ci_cd.sh)
- [run_tests.sh](https://github.com/faberNovel/docker-android/blob/develop/tests/run_tests.sh)
- [desc.sh](https://github.com/faberNovel/docker-android/blob/develop/desc/desc.sh)

Those scripts are using posix shell as they were run using docker image without bash. We should double check our ci / cd process (our GitHub Action) could support moving back to bash shell.

**Comment by vincentbrison** [comment]
For example [cd_prepare_release.yml](https://github.com/faberNovel/docker-android/blob/develop/.github/workflows/cd_prepare_release.yml), we are using `docker://alpine/git:v2.24.3` which do not come with bash installed.

We could switch to ubuntu image which should come with git and bash installed.

(The idea behind using docker image to run CI is to be fully independent on software running in GitHub runner).

**Comment by sjcqs** [comment]
I'm not sure we should force the usage of bash. 
In the Google guide, they are using bash to be consistent.

If there's an added value to switch to bash, ok, but in our case we don't really need it imo.

**Comment by vincentbrison** [comment]
Agreed, not sure its worth the effort for now 🤷‍♂️

**Comment by vincentbrison** [comment]
We would re open this when if needed. Thanks for concern.
