### ISSUE TITLE
Improve Action testing

### ISSUE THREAD

**Issue by vincentbrison** [faberNovel/docker-android#79]
Currently the action is tested using the same tests as the image (check [ci_action.yml](https://github.com/faberNovel/docker-android/blob/develop/.github/workflows/ci_action.yml)).
This leads to issues as the action is relying on a pre compiled image pulled of DockerHub, and thus, any change in the image reflected in the tests will break in the action.
We could create a specific test suite for the action, as we do not need to test the image itself, but whether if the action is working or not (ability to pull image, to run a basic fastlane command, correctness in inputs reading).

**Comment by sjcqs** [comment]
Instead of launching them in every PR they could be run either:
- When making a release (against snapshot images)
- Nightly (against snapshot images)

**Comment by vincentbrison** [comment]
Conceptually, it looks weird to run tests coming from the docker image for the action. It is like we are testing two times the same thing, like if we did not have confidence into our tests for the docker image.
@sjcqs do you still think we should run the same test suite, but only on release or nightly? I think it could be overwhelming, as when doing a release, everything should already be tested. You do not want to fix something broke, when doing a release.

**Comment by sjcqs** [comment]
Since the Github Action is really simple and just wraps our images, we could get rid of the tests on it, yes 🤷.

**Comment by vincentbrison** [comment]
Ok, I will look into building a specific test suite for the action then 👍
