### ISSUE TITLE
Cannot install new ruby version with rbenv

### ISSUE THREAD

**Issue by kelianClerc** [faberNovel/docker-android#80]
Cannot access `install` command for rbenv from a github action. This command is well installed via 
```
# Install ruby-build (rbenv plugin)
RUN mkdir -p "$RBENV_HOME"/plugins
RUN git clone https://github.com/rbenv/ruby-build.git "$RBENV_HOME"/plugins/ruby-build
```

But when trying to run it from a github action, I've got the following error :
https://github.com/faberNovel/faberdemo-android/runs/923377141?check_suite_focus=true

According to stackoverflow, to load plugins, a configuration is missing
https://stackoverflow.com/a/24249090/7301610

**Comment by sjcqs** [comment]
After some digging with @kelianClerc: 
- Github Action is changing HOME env var to `/github/workspace`
Thus, rbenv plugins are not available anymore. 

To fix it `RBENV_ROOT` need to be set.
