### ISSUE TITLE
Add support of different JDK versions

### ISSUE THREAD

**Issue by ferrandp** [faberNovel/docker-android#93]
In some projects, the current JDK (11) is not supported and brings some compilation issues (https://github.com/google/dagger/issues/1449 for example).

One solution would be to expose JDK 8 and the latest JDK, plus a tool to switch between JDK versions (Jenv for example).

**Comment by vincentbrison** [comment]
Some context here:
- Android Studio comes with its own jdk (8 I guess) to avoid jdk compatibility issue.
- Annotation processor needs to honor source compatility with recent jdk and kotlin version, which is the case for [AssistedInject](https://github.com/square/AssistedInject/blob/master/CHANGELOG.md#version-052-2019-11-22) for example. Not updated annotation processor would not honor those contract and would failed build using recent jdks.

We could provide the same level of support as Android Studio does, so provide the same JDK + the most recent stable JDK to not old back devs using updated tooling.

The best way to provide multiple jdk support is to use [jenv](https://www.jenv.be/) imho. What do you think about it @sjcqs ?
